package com.swiftcart.review_service.mapper;

import com.swiftcart.review_service.dtos.ReviewRequest;
import com.swiftcart.review_service.dtos.ReviewResponse;
import com.swiftcart.review_service.model.Review;
import org.springframework.stereotype.Component;

@Component
public class ReviewMapper {

    public Review toEntity(ReviewRequest request) {
        Review review = new Review();
        // Use standard getters generated by Lombok
        review.setProductId(request.getProductId());
        review.setUserId(request.getUserId());
        review.setUserName(request.getUserName());
        review.setContent(request.getContent());
        review.setRating(request.getRating());
        return review;
    }

    public ReviewResponse toDto(Review review) {
        ReviewResponse response = new ReviewResponse();
        response.setId(review.getId());
        response.setProductId(review.getProductId());
        response.setUserId(review.getUserId());
        response.setUserName(review.getUserName());
        response.setContent(review.getContent());
        response.setRating(review.getRating());
        response.setCreatedAt(review.getCreatedAt());
        return response;
    }
}