server:
  port: 8084

spring:
  application:
    name: warranty-service
  datasource:
    url: jdbc:mysql://localhost:3306/swiftcart_warranty_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/